# Generated by Django 2.1.1 on 2018-09-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berkas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Berkas')),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keterangan Berkas')),
            ],
        ),
    ]
