# Generated by Django 2.1.1 on 2018-09-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berkas',
            options={'verbose_name': 'Data Berkas', 'verbose_name_plural': 'Data Berkas'},
        ),
    ]
