# Generated by Django 2.1.1 on 2018-09-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0002_auto_20180910_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='berkas',
            name='berkas',
            field=models.FileField(default=1, upload_to='', verbose_name='Berkas'),
            preserve_default=False,
        ),
    ]
