# Generated by Django 2.1.1 on 2018-09-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0003_berkas_berkas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkas',
            name='berkas',
            field=models.FileField(upload_to='uploads/', verbose_name='Berkas'),
        ),
    ]
