# Generated by Django 2.1.1 on 2018-09-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0004_auto_20180910_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkas',
            name='berkas',
            field=models.FileField(upload_to='media/uploads/', verbose_name='Berkas'),
        ),
    ]
