# Generated by Django 2.1.1 on 2018-09-17 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dokumen', '0005_auto_20180917_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='berkas',
            name='upload_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Diupload oleh'),
            preserve_default=False,
        ),
    ]
